export const LIST = "LIST";
export type LIST = typeof LIST;

export const GET = "GET";
export type GET = typeof GET;

export const CREATE = "CREATE";
export type CREATE = typeof CREATE;

export const UPDATE = "UPDATE";
export type UPDATE = typeof UPDATE;

export const DELETE = "DELETE";
export type DELETE = typeof DELETE;

export const CREATE_MULTI = "CREATE_MULTI";
export type CREATE_MULTI = typeof CREATE_MULTI;

// Static Category
export const LIST_STATIC_CATEGORY = "LIST_STATIC_CATEGORY";
export type LIST_STATIC_CATEGORY = typeof LIST_STATIC_CATEGORY;

export const CREATE_MULTI_STATIC_CATEGORIES = "CREATE_MULTI_STATIC_CATEGORIES";
export type CREATE_MULTI_STATIC_CATEGORIES = typeof CREATE_MULTI_STATIC_CATEGORIES;

export const UPDATE_STATIC_CATEGORY = "UPDATE_STATIC_CATEGORY";
export type UPDATE_STATIC_CATEGORY = typeof UPDATE_STATIC_CATEGORY;

export const REMOVE_STATIC_CATEGORY = "REMOVE_STATIC_CATEGORY";
export type REMOVE_STATIC_CATEGORY = typeof REMOVE_STATIC_CATEGORY;

// Dynamic Category
export const LIST_DYNAMIC_CATEGORY = "LIST_DYNAMIC_CATEGORY";
export type LIST_DYNAMIC_CATEGORY = typeof LIST_DYNAMIC_CATEGORY;

export const CREATE_MULTI_DYNAMIC_CATEGORIES = "CREATE_MULTI_DYNAMIC_CATEGORIES";
export type CREATE_MULTI_DYNAMIC_CATEGORIES = typeof CREATE_MULTI_DYNAMIC_CATEGORIES;

export const UPDATE_DYNAMIC_CATEGORY = "UPDATE_DYNAMIC_CATEGORY";
export type UPDATE_DYNAMIC_CATEGORY = typeof UPDATE_DYNAMIC_CATEGORY;

export const REMOVE_DYNAMIC_CATEGORY = "REMOVE_DYNAMIC_CATEGORY";
export type REMOVE_DYNAMIC_CATEGORY = typeof REMOVE_DYNAMIC_CATEGORY;
