// Static CLASS
export const LIST_STATIC_CLASS = "LIST_STATIC_CLASS";
export type LIST_STATIC_CLASS = typeof LIST_STATIC_CLASS;

export const CREATE_MULTI_STATIC_CLASS = "CREATE_MULTI_STATIC_CLASS";
export type CREATE_MULTI_STATIC_CLASS = typeof CREATE_MULTI_STATIC_CLASS;

export const UPDATE_STATIC_CLASS = "UPDATE_STATIC_CLASS";
export type UPDATE_STATIC_CLASS = typeof UPDATE_STATIC_CLASS;

export const REMOVE_STATIC_CLASS = "REMOVE_STATIC_CLASS";
export type REMOVE_STATIC_CLASS = typeof REMOVE_STATIC_CLASS;

// Dynamic CLASS
export const LIST_DYNAMIC_CLASS = "LIST_DYNAMIC_CLASS";
export type LIST_DYNAMIC_CLASS = typeof LIST_DYNAMIC_CLASS;

export const CREATE_MULTI_DYNAMIC_CATEGORIES = "CREATE_MULTI_DYNAMIC_CATEGORIES";
export type CREATE_MULTI_DYNAMIC_CATEGORIES = typeof CREATE_MULTI_DYNAMIC_CATEGORIES;

export const UPDATE_DYNAMIC_CLASS = "UPDATE_DYNAMIC_CLASS";
export type UPDATE_DYNAMIC_CLASS = typeof UPDATE_DYNAMIC_CLASS;

export const REMOVE_DYNAMIC_CLASS = "REMOVE_DYNAMIC_CLASS";
export type REMOVE_DYNAMIC_CLASS = typeof REMOVE_DYNAMIC_CLASS;
