// Static GROUP
export const LIST_STATIC_GROUP = "LIST_STATIC_GROUP";
export type LIST_STATIC_GROUP = typeof LIST_STATIC_GROUP;

export const CREATE_MULTI_STATIC_GROUP = "CREATE_MULTI_STATIC_GROUP";
export type CREATE_MULTI_STATIC_GROUP = typeof CREATE_MULTI_STATIC_GROUP;

export const UPDATE_STATIC_GROUP = "UPDATE_STATIC_GROUP";
export type UPDATE_STATIC_GROUP = typeof UPDATE_STATIC_GROUP;

export const REMOVE_STATIC_GROUP = "REMOVE_STATIC_GROUP";
export type REMOVE_STATIC_GROUP = typeof REMOVE_STATIC_GROUP;

// Dynamic GROUP
export const GET_TOTAL_PAGE_DYNAMIC_GROUP = "GET_TOTAL_PAGE_DYNAMIC_GROUP";
export type GET_TOTAL_PAGE_DYNAMIC_GROUP = typeof GET_TOTAL_PAGE_DYNAMIC_GROUP;

export const LIST_DYNAMIC_GROUP = "LIST_DYNAMIC_GROUP";
export type LIST_DYNAMIC_GROUP = typeof LIST_DYNAMIC_GROUP;

export const CREATE_MULTI_DYNAMIC_GROUPS = "CREATE_MULTI_DYNAMIC_GROUPS";
export type CREATE_MULTI_DYNAMIC_GROUPS = typeof CREATE_MULTI_DYNAMIC_GROUPS;

export const UPDATE_DYNAMIC_GROUP = "UPDATE_DYNAMIC_GROUP";
export type UPDATE_DYNAMIC_GROUP = typeof UPDATE_DYNAMIC_GROUP;

export const REMOVE_DYNAMIC_GROUP = "REMOVE_DYNAMIC_GROUP";
export type REMOVE_DYNAMIC_GROUP = typeof REMOVE_DYNAMIC_GROUP;
