// Static Category
export const LIST_STATIC_ORDER = "LIST_STATIC_ORDER";
export type LIST_STATIC_ORDER = typeof LIST_STATIC_ORDER;

export const CREATE_MULTI_STATIC_ORDERS = "CREATE_MULTI_STATIC_ORDERS";
export type CREATE_MULTI_STATIC_ORDERS = typeof CREATE_MULTI_STATIC_ORDERS;

export const UPDATE_STATIC_ORDER = "UPDATE_STATIC_ORDER";
export type UPDATE_STATIC_ORDER = typeof UPDATE_STATIC_ORDER;

export const REMOVE_STATIC_ORDER = "REMOVE_STATIC_ORDER";
export type REMOVE_STATIC_ORDER = typeof REMOVE_STATIC_ORDER;

// Dynamic Category
export const GET_TOTAL_PAGE_DYNAMIC_ORDER = "GET_TOTAL_PAGE_DYNAMIC_ORDER";
export type GET_TOTAL_PAGE_DYNAMIC_ORDER = typeof GET_TOTAL_PAGE_DYNAMIC_ORDER;

export const LIST_DYNAMIC_ORDER = "LIST_DYNAMIC_ORDER";
export type LIST_DYNAMIC_ORDER = typeof LIST_DYNAMIC_ORDER;

export const CREATE_MULTI_DYNAMIC_ORDERS = "CREATE_MULTI_DYNAMIC_ORDERS";
export type CREATE_MULTI_DYNAMIC_ORDERS = typeof CREATE_MULTI_DYNAMIC_ORDERS;

export const UPDATE_DYNAMIC_ORDER = "UPDATE_DYNAMIC_ORDER";
export type UPDATE_DYNAMIC_ORDER = typeof UPDATE_DYNAMIC_ORDER;

export const REMOVE_DYNAMIC_ORDER = "REMOVE_DYNAMIC_ORDER";
export type REMOVE_DYNAMIC_ORDER = typeof REMOVE_DYNAMIC_ORDER;


// Product with supplier
export const GET_PRODUCTS_BELONG_SUPPLIER = "GET_PRODUCTS_BELONG_SUPPLIER";
export type GET_PRODUCTS_BELONG_SUPPLIER = typeof GET_PRODUCTS_BELONG_SUPPLIER;