// Static Category
export const LIST_STATIC_PRODUCT = "LIST_STATIC_PRODUCT";
export type LIST_STATIC_PRODUCT = typeof LIST_STATIC_PRODUCT;

export const CREATE_MULTI_STATIC_PRODUCTS = "CREATE_MULTI_STATIC_PRODUCTS";
export type CREATE_MULTI_STATIC_PRODUCTS = typeof CREATE_MULTI_STATIC_PRODUCTS;

export const UPDATE_STATIC_PRODUCT = "UPDATE_STATIC_PRODUCT";
export type UPDATE_STATIC_PRODUCT = typeof UPDATE_STATIC_PRODUCT;

export const REMOVE_STATIC_PRODUCT = "REMOVE_STATIC_PRODUCT";
export type REMOVE_STATIC_PRODUCT = typeof REMOVE_STATIC_PRODUCT;

// Dynamic Category
export const GET_TOTAL_PAGE_DYNAMIC_PRODUCT = "GET_TOTAL_PAGE_DYNAMIC_PRODUCT";
export type GET_TOTAL_PAGE_DYNAMIC_PRODUCT = typeof GET_TOTAL_PAGE_DYNAMIC_PRODUCT;

export const LIST_DYNAMIC_PRODUCT = "LIST_DYNAMIC_PRODUCT";
export type LIST_DYNAMIC_PRODUCT = typeof LIST_DYNAMIC_PRODUCT;

export const CREATE_MULTI_DYNAMIC_PRODUCTS = "CREATE_MULTI_DYNAMIC_PRODUCTS";
export type CREATE_MULTI_DYNAMIC_PRODUCTS = typeof CREATE_MULTI_DYNAMIC_PRODUCTS;

export const UPDATE_DYNAMIC_PRODUCT = "UPDATE_DYNAMIC_PRODUCT";
export type UPDATE_DYNAMIC_PRODUCT = typeof UPDATE_DYNAMIC_PRODUCT;

export const REMOVE_DYNAMIC_PRODUCT = "REMOVE_DYNAMIC_PRODUCT";
export type REMOVE_DYNAMIC_PRODUCT = typeof REMOVE_DYNAMIC_PRODUCT;