// Static SUPPLIER
export const LIST_STATIC_SUPPLIER = "LIST_STATIC_SUPPLIER";
export type LIST_STATIC_SUPPLIER = typeof LIST_STATIC_SUPPLIER;

export const CREATE_MULTI_STATIC_SUPPLIER = "CREATE_MULTI_STATIC_SUPPLIER";
export type CREATE_MULTI_STATIC_SUPPLIER = typeof CREATE_MULTI_STATIC_SUPPLIER;

export const UPDATE_STATIC_SUPPLIER = "UPDATE_STATIC_SUPPLIER";
export type UPDATE_STATIC_SUPPLIER = typeof UPDATE_STATIC_SUPPLIER;

export const REMOVE_STATIC_SUPPLIER = "REMOVE_STATIC_SUPPLIER";
export type REMOVE_STATIC_SUPPLIER = typeof REMOVE_STATIC_SUPPLIER;

// Dynamic SUPPLIER
export const GET_TOTAL_PAGE_DYNAMIC_SUPPLIERS = "GET_TOTAL_PAGE_DYNAMIC_SUPPLIERS";
export type GET_TOTAL_PAGE_DYNAMIC_SUPPLIERS = typeof GET_TOTAL_PAGE_DYNAMIC_SUPPLIERS;

export const LIST_DYNAMIC_SUPPLIER = "LIST_DYNAMIC_SUPPLIER";
export type LIST_DYNAMIC_SUPPLIER = typeof LIST_DYNAMIC_SUPPLIER;

export const CREATE_MULTI_DYNAMIC_SUPPLIERS = "CREATE_MULTI_DYNAMIC_SUPPLIERS";
export type CREATE_MULTI_DYNAMIC_SUPPLIERS = typeof CREATE_MULTI_DYNAMIC_SUPPLIERS;

export const UPDATE_DYNAMIC_SUPPLIER = "UPDATE_DYNAMIC_SUPPLIER";
export type UPDATE_DYNAMIC_SUPPLIER = typeof UPDATE_DYNAMIC_SUPPLIER;

export const REMOVE_DYNAMIC_SUPPLIER = "REMOVE_DYNAMIC_SUPPLIER";
export type REMOVE_DYNAMIC_SUPPLIER = typeof REMOVE_DYNAMIC_SUPPLIER;
