import React from 'react';

import {Layout} from 'antd';

import "./style.css";

const {Content} = Layout;

export default class MainContent extends React.Component<IMainContentProps, IMainContentState> {
    constructor(props: IMainContentProps){
        super(props);
    }

    render(){
        return (
            <Content className="main-content">
                        <div className="div-main-content">
                            ...
                  <br />
                            Really
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            long
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            content
                </div>
                    </Content>
        );
    }
}

interface IMainContentProps {

}

interface IMainContentState {

}