import React from 'react';

import {Layout} from 'antd';

import ProductOrder from '../../pages/ProductOrder';

import "./styles.scss";

import {AuthState} from '../../store/auth/types';
import {checkAuthenticate} from '../../store/auth/actions';
import { AppState } from '../../store';
import { connect } from 'react-redux';

const {Content} = Layout;


interface IMainContentProps {
    checkAuthenticate: typeof checkAuthenticate,
    auth: AuthState,
}

interface IMainContentState {

}

class MainContent extends React.Component<IMainContentProps, IMainContentState> {
    constructor(props: IMainContentProps){
        super(props);

        props.checkAuthenticate(props.auth);
    }

    render(){
        return (
            <Content className="main-content">
                        <div className="div-main-content">
                            <ProductOrder></ProductOrder>
                            {/* ...
                  <br />
                            Really
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            long
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            ...
                  <br />
                            content */}
                </div>
                    </Content>
        );
    }
}


const mapStateToProps = (state: AppState) => ({
    auth: state.auth,
});

export default connect(
    mapStateToProps,
    {
        checkAuthenticate
    }
)(MainContent);
